security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users_in_memory:
            memory:
                users:
                # mettre l'uid cas du testeur todo: faire le lien avec la bdd
                    uidcasuser:  { roles: [ 'ROLE_USER' ] }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            access_token:
                token_handler:
                    cas:
                        validation_url: '%cas_validate_url%'
                token_extractors:
                    - security.access_token_extractor.cas
            entry_point: App\Security\CasAuthenticatorEntryPoint
    access_control:
         - { path: ^/meteo, roles: 'ROLE_USER' }
         - { path: ^/signaler, roles: 'ROLE_USER' }
         - { path: ^/application, roles: 'ROLE_ADMIN' }
         - { path: ^/maintenance, roles: 'ROLE_ADMIN' }
