security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: uuid
    firewalls:
        main:
            provider: app_user_provider
            access_token:
                token_handler:
                    cas:
                        validation_url: '%cas_validate_url%'
                token_extractors:
                    - security.access_token_extractor.cas
            entry_point: App\Security\CasAuthenticatorEntryPoint
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    access_control:
         - { path: ^/meteo, roles: 'ROLE_USER' }
         - { path: ^/signaler, roles: 'ROLE_USER' }
         - { path: ^/application, roles: 'ROLE_ADMIN' }
         - { path: ^/maintenance, roles: 'ROLE_ADMIN' }
         - { path: ^/user, roles: 'ROLE_SUPER_ADMIN' }
         - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: 'ROLE_SUPER_ADMIN' }
