# config/packages/prod/monolog.yaml
monolog:
    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            enabled: false

        syslog_handler:
            type: syslog
            priority: 10 # called first
            level: error
